---
title: "DATA3888 Optiver Project EDA"
format: html
editor: visual
---

# EDA Stock 0

```{r}
library(ggplot2)
library(dplyr)
library(rugarch)
```

```{r}
stock0 <- read.csv("individual_book_train/stock_0.csv")
head(stock0)
```

$$
BidAskSpread = \frac{\text{BestOffer}}{\text{BestBid}} - 1
\\
WAP = \frac{\text{BidPrice}_1\cdot\text{AskSize}_1+\text{AskPrice}_1\cdot\text{BidSize}_1} {\text{BidSize}\_1+\text{AskSize}\_1}
$$

## Lab4A Code

```{r}
# Calculating WAP and BAS
stock0 <- stock0 |> mutate(
  WAP = (bid_price1 * ask_size1 + ask_price1 * bid_size1) / (bid_size1 + ask_size1))
stock0 <- stock0|> mutate(BidAskSpread = ask_price1 / bid_price1 - 1)
head(stock0)
```

```{r}
# computes the log returns
log_r1 <- list()
time_IDs <- unique(stock0[, 1])[1:500]
for (i in 1 : length(time_IDs)) {
  sec <- stock0 |>
    filter(time_id == time_IDs[i]) |>
    pull(seconds_in_bucket)
  price <- stock0 |>
    filter(time_id == time_IDs[i]) |>
    pull(WAP)
  log_r <- log(price[-1] / price[1:(length(price) - 1)])
  log_r1[[i]] <- data.frame(time = sec[-1], log_return = log_r)
  time.no.change <- (1:600)[!(1:600 %in% log_r1[[i]]$time)]
  if (length(time.no.change) > 0) {
    new.df <- data.frame(time = time.no.change, log_return = 0)
    log_r1[[i]] <- rbind(log_r1[[i]], new.df)
    log_r1[[i]] <- log_r1[[i]][order(log_r1[[i]]$time), ]
  }
}
```

```{r}
# computes the volatility
vol <- list()
comp_vol <- function(x) {
  return(sqrt(sum(x ^ 2)))
}
for (i in 1 : length(log_r1)) {
  log_r1[[i]] <- log_r1[[i]] |> mutate(time_bucket = ceiling(time / 30))
  vol[[i]] <- aggregate(log_return ~ time_bucket, data = log_r1[[i]], FUN = comp_vol)
  colnames(vol[[i]]) <- c('time_bucket', 'volatility')
}
```

```{r}
ggplot(data = log_r1[[1]], aes(x = time, y = log_return)) + geom_line() 
```

```{r}
ggplot(data = vol[[1]], aes(x = time_bucket, y = volatility)) + geom_line() + geom_point() 
```
